name: huurdersapp
# name: navigation_drawer_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  expandable: ^5.0.1
  logger: ^1.1.0
  http: ^0.13.4
  typicons_flutter: ^0.5.0
  line_awesome_flutter: ^2.0.0
  font_awesome_flutter: ^10.1.0
  syncfusion_flutter_pdfviewer: ^20.1.47-beta
  lottie: ^1.2.2
  flutter_launcher_icons: ^0.9.2
  webview_flutter: ^2.8.0
  flutter_html: ^2.2.1
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon-Store.png" 
  adaptive_icon_background: "assets/Icon-Store.png"
  adaptive_icon_foreground: "assets/Icon-Store.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
  - family: Nunito
    fonts:
    - asset: fonts/Nunito-ExtraLight.ttf
    - asset: fonts/Nunito-Light.ttf
    - asset: fonts/Nunito-Regular.ttf
